<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Request extends \AppBundle\Entity\Request implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'objet', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'fistrequestDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'budget', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'requestDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'statusChangeDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'raison', 'payementProcess', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'acceptedUntilDate');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'objet', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'fistrequestDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'budget', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'requestDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'statusChangeDate', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'raison', 'payementProcess', '' . "\0" . 'AppBundle\\Entity\\Request' . "\0" . 'acceptedUntilDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Request $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestDate($requestDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestDate', array($requestDate));

        return parent::setRequestDate($requestDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestDate', array());

        return parent::getRequestDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusChangeDate($statusChangeDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusChangeDate', array($statusChangeDate));

        return parent::setStatusChangeDate($statusChangeDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusChangeDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusChangeDate', array());

        return parent::getStatusChangeDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaison($raison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaison', array($raison));

        return parent::setRaison($raison);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaison', array());

        return parent::getRaison();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet($objet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', array($objet));

        return parent::setObjet($objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', array());

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setFistrequestDate($fistrequestDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFistrequestDate', array($fistrequestDate));

        return parent::setFistrequestDate($fistrequestDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFistrequestDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFistrequestDate', array());

        return parent::getFistrequestDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudget($budget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudget', array($budget));

        return parent::setBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudget', array());

        return parent::getBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptedUntilDate($acceptedUntilDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptedUntilDate', array($acceptedUntilDate));

        return parent::setAcceptedUntilDate($acceptedUntilDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptedUntilDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptedUntilDate', array());

        return parent::getAcceptedUntilDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayementProcess(\AppBundle\Entity\PayementProcess $payementProcess = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayementProcess', array($payementProcess));

        return parent::setPayementProcess($payementProcess);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayementProcess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayementProcess', array());

        return parent::getPayementProcess();
    }

}
