<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payement extends \AppBundle\Entity\Payement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'orangeMoney', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'mtnMoney', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'payementLivraison', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'moneyTransfert', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'defined', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'mobileTransfert', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'apresReception', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'fournie', 'requestForVerification');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'orangeMoney', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'mtnMoney', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'payementLivraison', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'moneyTransfert', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'defined', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'mobileTransfert', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'apresReception', '' . "\0" . 'AppBundle\\Entity\\Payement' . "\0" . 'fournie', 'requestForVerification');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrangeMoney($orangeMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrangeMoney', array($orangeMoney));

        return parent::setOrangeMoney($orangeMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrangeMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrangeMoney', array());

        return parent::getOrangeMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setMtnMoney($mtnMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMtnMoney', array($mtnMoney));

        return parent::setMtnMoney($mtnMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getMtnMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMtnMoney', array());

        return parent::getMtnMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoneyTransfert($moneyTransfert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoneyTransfert', array($moneyTransfert));

        return parent::setMoneyTransfert($moneyTransfert);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoneyTransfert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoneyTransfert', array());

        return parent::getMoneyTransfert();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirified($virified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirified', array($virified));

        return parent::setVirified($virified);
    }

    /**
     * {@inheritDoc}
     */
    public function getVirified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirified', array());

        return parent::getVirified();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirifiedAt($virifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirifiedAt', array($virifiedAt));

        return parent::setVirifiedAt($virifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getVirifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirifiedAt', array());

        return parent::getVirifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassType', array());

        return parent::getClassType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayementLivraison($payementLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayementLivraison', array($payementLivraison));

        return parent::setPayementLivraison($payementLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayementLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayementLivraison', array());

        return parent::getPayementLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setApresReception($apresReception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApresReception', array($apresReception));

        return parent::setApresReception($apresReception);
    }

    /**
     * {@inheritDoc}
     */
    public function getApresReception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApresReception', array());

        return parent::getApresReception();
    }

    /**
     * {@inheritDoc}
     */
    public function setFournie($fournie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFournie', array($fournie));

        return parent::setFournie($fournie);
    }

    /**
     * {@inheritDoc}
     */
    public function getFournie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFournie', array());

        return parent::getFournie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefined($defined)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefined', array($defined));

        return parent::setDefined($defined);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefined()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefined', array());

        return parent::getDefined();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileTransfert($mobileTransfert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileTransfert', array($mobileTransfert));

        return parent::setMobileTransfert($mobileTransfert);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileTransfert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileTransfert', array());

        return parent::getMobileTransfert();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerificationRequestedAt($verificationRequestedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerificationRequestedAt', array($verificationRequestedAt));

        return parent::setVerificationRequestedAt($verificationRequestedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerificationRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerificationRequestedAt', array());

        return parent::getVerificationRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestForVerification(\AppBundle\Entity\Request $requestForVerification = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestForVerification', array($requestForVerification));

        return parent::setRequestForVerification($requestForVerification);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestForVerification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestForVerification', array());

        return parent::getRequestForVerification();
    }

}
