<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'uniqueid', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'email', 'password', 'plainPassword', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'accountNonExpired', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'credentialsNonExpired', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'accountNonLocked', 'fiscalite', 'localisation', 'representation', 'contact', 'origine', 'livraison', 'payement', 'retour', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'virified', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'virifiedAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'certified', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'certifiedAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roles');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'uniqueid', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'email', 'password', 'plainPassword', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'accountNonExpired', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'credentialsNonExpired', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'accountNonLocked', 'fiscalite', 'localisation', 'representation', 'contact', 'origine', 'livraison', 'payement', 'retour', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'virified', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'virifiedAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'certified', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'certifiedAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roles');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', array());

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', array($password));

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqueid($uniqueid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqueid', array($uniqueid));

        return parent::setUniqueid($uniqueid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueid', array());

        return parent::getUniqueid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiscalite(\AppBundle\Entity\Fiscalite $fisacalite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiscalite', array($fisacalite));

        return parent::setFiscalite($fisacalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiscalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiscalite', array());

        return parent::getFiscalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation(\AppBundle\Entity\Localisation $localisation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', array($localisation));

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', array());

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\AppBundle\Entity\Contact $contact = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigine(\AppBundle\Entity\Origine $origine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigine', array($origine));

        return parent::setOrigine($origine);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigine', array());

        return parent::getOrigine();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivraison(\AppBundle\Entity\Livraison $livraison = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivraison', array($livraison));

        return parent::setLivraison($livraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivraison', array());

        return parent::getLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayement(\AppBundle\Entity\Payement $payement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayement', array($payement));

        return parent::setPayement($payement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayement', array());

        return parent::getPayement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetour(\AppBundle\Entity\Retour $retour = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetour', array($retour));

        return parent::setRetour($retour);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetour', array());

        return parent::getRetour();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentation(\AppBundle\Entity\Representation $representation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentation', array($representation));

        return parent::setRepresentation($representation);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentation', array());

        return parent::getRepresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirified($virified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirified', array($virified));

        return parent::setVirified($virified);
    }

    /**
     * {@inheritDoc}
     */
    public function getVirified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirified', array());

        return parent::getVirified();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirifiedAt($virifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirifiedAt', array($virifiedAt));

        return parent::setVirifiedAt($virifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getVirifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVirifiedAt', array());

        return parent::getVirifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertified($certified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertified', array($certified));

        return parent::setCertified($certified);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertified', array());

        return parent::getCertified();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertifiedAt($certifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertifiedAt', array($certifiedAt));

        return parent::setCertifiedAt($certifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertifiedAt', array());

        return parent::getCertifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($ceatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($ceatedAt));

        return parent::setCreatedAt($ceatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

}
