<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function findByLocality($pays=null,$ville=null)
{
        $qb = $this->createQueryBuilder('e') 
   	    ->where('(e.ville is NULL and e.pays is NULL) or (e.ville is NULL and e.pays=:pays) or (e.ville =:ville and e.pays=:pays)')
   	    ->setParameter('pays', $pays)
   	    ->setParameter('ville', $ville)  
         ->andWhere('e.endDate>=:endDate')->setParameter('endDate', new \DateTime());
    return $qb->getQuery()->getResult();
}
}
