<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{


public function findByUser($user)
{
  $qb = $this->createQueryBuilder('p')
->where('p.user=:user')->setParameter('user', $user);   
  return $qb;
}

}
