AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: telephone
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        telephone:
            - NotBlank:  ~
            - Type: string
        plainPassword:
            - NotBlank: { groups: ['changePasseword'] }
            - Type: string
            - Length:
                min: 4
                max: 50


AppBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - Type: string
