AppBundle\Entity\Fiscalite:
    exclusion_policy: none
    properties:
        id:
            groups: ['fiscalite','user','full' ]
        nomJuridique:
            groups: ['fiscalite','full'  ]
        registre:
            groups: ['fiscalite','full'  ]
        contribuable:
            groups: ['fiscalite','full'  ]
        categorie:
            groups: ['fiscalite','full'  ]
        regime:
            groups: ['fiscalite','full'  ]
        conforme:
            groups: ['fiscalite','full'  ] 
        defined:
            groups: ['full'  ] 
        fournie:
            groups: ['full'  ]      
        requestForVerification:
            groups: ['fiscalite' , 'full' ]