AppBundle\Entity\Produit:
    exclusion_policy: none
    properties:
        id:
            groups: ['produit','full' ]
        nom:
            groups: ['produit' ,'full' ]
        prix:
            groups: ['produit','full' ] 
        description:
            groups: ['produit','full' ] 
        image:
            groups: ['produit','full']      
        descriptionLieu:
            groups: ['full' ] 
        lieu:
            groups: ['full' ]  
        lat:
            groups: ['full' ] 
        lon:
            groups: ['full' ] 
        utilDate:
            groups: ['full' ] 
        utilTime:
            groups: ['full' ]                                    
        prix:
            groups: ['produit' ,'full']  
        prixDiscutable:
            groups: ['produit' ,'full']     
        origine:
            groups: ['produit' ,'full']  
        livraison:
            groups: ['produit' ,'full']     
        payement:
            groups: ['produit' ,'full']  
        retour:
            groups: ['produit' ,'full']  
        publicites:
            groups: ['full']             