AppBundle\Entity\Contact:
    exclusion_policy: none
    properties:
        id:
            groups: ['contact','user','full' ]
        telephone:
            groups: ['contact','full'  ]
        email:
            groups: ['contact','full'  ]
        whatsapp:
            groups: ['contact','full'  ]
        fecebook:
            groups: ['contact','full'  ]
        site:
            groups: ['contact','full'  ]
        defined:
            groups: ['full'  ] 
        fournie:
            groups: ['full'  ]             
        requestForVerification:
            groups: ['contact' , 'full' ]
    