AppBundle\Entity\Livraison:
    exclusion_policy: none
    properties:
        id:
            groups: ['livraison','produit','user','full' ]
        internationnal:
            groups: ['livraison','full'  ]
        delais:
            groups: ['livraison','full'  ]
        support:
            groups: ['livraison','full'  ]
        expedition:
            groups: ['livraison','full'  ]
        domicile:
            groups: ['livraison','full'  ]
        enMagazin:
            groups: ['livraison','full'  ] 
        toutLePays:
            groups: ['livraison','full'  ] 
        defined:
            groups: ['full'  ] 
 
        fournie:
            groups: ['full'  ] 
        requestForVerification:
            groups: ['livraison', 'full' ]                                               